#cloud-config

rancher:
  password: root99
  docker:
    engine: docker-18.09.2
  network:
    interfaces:
      eth0:
        mtu: 1500
        dhcp: true
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4

  console: ubuntu


  
